/**
 * PDF Service - Generates professional PDF documents for ordinances and resolutions.
 */
const PDFDocument = require('pdfkit');

/**
 * Formats a date value for display in the PDF.
 * @param {string|Date|null} value
 * @returns {string}
 */
function formatDate(value) {
  if (!value) return 'N/A';
  return new Date(value).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

/**
 * Writes the common document header (logo area, system name, divider).
 * @param {PDFDocument} doc
 * @param {string} documentType  e.g. 'ORDINANCE' or 'RESOLUTION'
 */
function writeHeader(doc, documentType) {
  // Add left and right logos (replace with actual file paths)
  const leftLogoPath = 'public/logo-left.png'; // Update with actual path
  const rightLogoPath = 'public/logo-right.png'; // Update with actual path
  const logoSize = 50;
  const { width: pageWidth, margins: { left: marginLeft, right: marginRight } } = doc.page;
  const {y} = doc;
  try {
    doc.image(leftLogoPath, marginLeft, y, { width: logoSize, height: logoSize });
  } catch {}
  try {
    doc.image(rightLogoPath, pageWidth - marginRight - logoSize, y, { width: logoSize, height: logoSize });
  } catch {}

  // Move y below logos
  doc.y = y + logoSize + 5;

  doc
    .fontSize(10)
    .fillColor('#666666')
    .text('Republic of the Philippines', { align: 'center' })
    .text('E-Legislative Monitoring System', { align: 'center' })
    .moveDown(0.3);

  doc
    .moveTo(doc.page.margins.left, doc.y)
    .lineTo(doc.page.width - doc.page.margins.right, doc.y)
    .strokeColor('#cccccc')
    .stroke()
    .moveDown(0.5);

  doc
    .fontSize(18)
    .fillColor('#1a1a2e')
    .font('Helvetica-Bold')
    .text(documentType, { align: 'center' })
    .moveDown(0.3);
}

/**
 * Writes a labeled metadata row (bold label + regular value on the same line).
 * @param {PDFDocument} doc
 * @param {string} label
 * @param {string} value
 */
function writeMetaRow(doc, label, value) {
  doc
    .font('Helvetica-Bold')
    .fontSize(10)
    .fillColor('#333333')
    .text(`${label}: `, { continued: true })
    .font('Helvetica')
    .fillColor('#555555')
    .text(value || 'N/A')
    .moveDown(0.2);
}

/**
 * Writes a section heading followed by body text.
 * @param {PDFDocument} doc
 * @param {string} heading
 * @param {string} body
 */
function writeSection(doc, heading, body) {
  doc
    .moveDown(0.6)
    .font('Helvetica-Bold')
    .fontSize(11)
    .fillColor('#1a1a2e')
    .text(heading)
    .moveDown(0.2)
    .font('Helvetica')
    .fontSize(10)
    .fillColor('#333333')
    .text(body || 'N/A', {
      align: 'justify',
      lineGap: 2,
    })
    .moveDown(0.2);
}

/**
 * Writes the common document footer on each page.
 * @param {PDFDocument} doc
 */
function writeFooter(doc) {
  const pages = doc.bufferedPageRange();
  for (let i = pages.start; i < pages.start + pages.count; i++) {
    doc.switchToPage(i);

    const footerY = doc.page.height - doc.page.margins.bottom + 10;

    doc
      .moveTo(doc.page.margins.left, footerY - 5)
      .lineTo(doc.page.width - doc.page.margins.right, footerY - 5)
      .strokeColor('#cccccc')
      .stroke();

    doc
      .font('Helvetica')
      .fontSize(8)
      .fillColor('#999999')
      .text(
        `Generated by E-Legislative Monitoring System  •  Page ${i + 1} of ${pages.count}`,
        doc.page.margins.left,
        footerY,
        { align: 'center', width: doc.page.width - doc.page.margins.left - doc.page.margins.right }
      );
  }
}

/**
 * Generates a PDF for an ordinance and pipes it to the provided writable stream.
 * @param {object} ordinance  - Ordinance record from the database
 * @param {import('stream').Writable} stream - Destination stream (e.g. HTTP response)
 */
function generateOrdinancePdf(ordinance, stream) {
  const doc = new PDFDocument({ margin: 60, bufferPages: true });
  doc.pipe(stream);

  writeHeader(doc, 'BARANGAY ORDINANCE');

  // Title
  doc
    .moveDown(0.5)
    .font('Helvetica-Bold')
    .fontSize(13)
    .fillColor('#1a1a2e')
    .text(ordinance.title || 'Untitled Ordinance', { align: 'center' })
    .moveDown(0.8);

  // Metadata block
  doc
    .moveTo(doc.page.margins.left, doc.y)
    .lineTo(doc.page.width - doc.page.margins.right, doc.y)
    .strokeColor('#eeeeee')
    .stroke()
    .moveDown(0.4);

  writeMetaRow(doc, 'Ordinance Number', ordinance.ordinance_number || 'Pending Assignment');
  writeMetaRow(doc, 'Status', ordinance.status);
  writeMetaRow(doc, 'Proposed By', ordinance.proposer_name || 'N/A');
  // Co-authors
  if (Array.isArray(ordinance.co_authors) && ordinance.co_authors.length > 0) {
    const coAuthorNames = ordinance.co_authors.map(c => c.name + (c.email ? ` <${c.email}>` : '')).join(', ');
    writeMetaRow(doc, 'Co-authors', coAuthorNames);
  }
  writeMetaRow(doc, 'Date Created', formatDate(ordinance.created_at));
  if (ordinance.approved_date) {
    writeMetaRow(doc, 'Date Approved', formatDate(ordinance.approved_date));
  }
  if (ordinance.published_date) {
    writeMetaRow(doc, 'Date Published', formatDate(ordinance.published_date));
  }

  doc
    .moveDown(0.4)
    .moveTo(doc.page.margins.left, doc.y)
    .lineTo(doc.page.width - doc.page.margins.right, doc.y)
    .strokeColor('#eeeeee')
    .stroke();

  // Sections
  if (ordinance.description) {
    writeSection(doc, 'Description', ordinance.description);
  }

  writeSection(doc, 'Full Content', ordinance.content);

  if (ordinance.remarks) {
    writeSection(doc, 'Remarks', ordinance.remarks);
  }

  writeFooter(doc);
  doc.end();
}

/**
 * Generates a PDF for a resolution and pipes it to the provided writable stream.
 * @param {object} resolution  - Resolution record from the database
 * @param {import('stream').Writable} stream - Destination stream (e.g. HTTP response)
 */
function generateResolutionPdf(resolution, stream) {
  const doc = new PDFDocument({ margin: 60, bufferPages: true });
  doc.pipe(stream);

  writeHeader(doc, 'BARANGAY RESOLUTION');

  // Title
  doc
    .moveDown(0.5)
    .font('Helvetica-Bold')
    .fontSize(13)
    .fillColor('#1a1a2e')
    .text(resolution.title || 'Untitled Resolution', { align: 'center' })
    .moveDown(0.8);

  // Metadata block
  doc
    .moveTo(doc.page.margins.left, doc.y)
    .lineTo(doc.page.width - doc.page.margins.right, doc.y)
    .strokeColor('#eeeeee')
    .stroke()
    .moveDown(0.4);

  writeMetaRow(doc, 'Resolution Number', resolution.resolution_number || 'Pending Assignment');
  writeMetaRow(doc, 'Status', resolution.status);
  writeMetaRow(doc, 'Proposed By', resolution.proposer_name || 'N/A');
  writeMetaRow(doc, 'Date Created', formatDate(resolution.created_at));
  if (resolution.approved_date) {
    writeMetaRow(doc, 'Date Approved', formatDate(resolution.approved_date));
  }
  if (resolution.published_date) {
    writeMetaRow(doc, 'Date Published', formatDate(resolution.published_date));
  }

  doc
    .moveDown(0.4)
    .moveTo(doc.page.margins.left, doc.y)
    .lineTo(doc.page.width - doc.page.margins.right, doc.y)
    .strokeColor('#eeeeee')
    .stroke();

  // Sections
  if (resolution.description) {
    writeSection(doc, 'Description', resolution.description);
  }

  writeSection(doc, 'Full Text', resolution.content);

  if (resolution.remarks) {
    writeSection(doc, 'Notes', resolution.remarks);
  }

  writeFooter(doc);
  doc.end();
}

module.exports = { generateOrdinancePdf, generateResolutionPdf };
