services:
  - type: web
    name: elegislative-api
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /auth/refresh
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: CORS_ORIGINS
        value: https://elegislative.lits.com.ph
      - key: PORT
        value: 10000
      - key: DB_USER
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_PORT
        sync: false
      - key: JWT_SECRET
        sync: false
